import { create } from "zustand";

export const useStateManager = create((set) => ({
  selectedUser: null,                                 
  setSelectedUser: (selectedUser) => set({ selectedUser }),
  messages: [],
  setMessages: (messages) => set({ messages }),
  socket: null,
  setSocket: (socket) => set({ socket }),
  onlineUsers: [],
  setOnlineUsers: (onlineUsers) => set({ onlineUsers }),
  socketId: null,
  setSocketId: (socketId) => set({ socketId }),
  newMessage: [],
  setNewMessage: (newMessage) => set({ newMessage }),
  user: [],
  setUser: (user) => set({ user }),
  courses: [],
  setCourses: (courses) => set({ courses }),
  image: [],
  setImage: (image) => set({ image }),
  myChatUsers: [],
  setMyChatUsers: (myChatUsers) => set({ myChatUsers }),
  allUsers: [],
  setAllUsers: (allUsers) => set({ allUsers }),
  divisionDisplay: false,
  setDivisionDisplay: (divisionDisplay) => set({ divisionDisplay }),
  messageSearch: "",
  setMessageSearch: (messageSearch) => set({ messageSearch }),
  selectedGroup: null,
  setSelectedGroup: (selectedGroup) => set({ selectedGroup }),
  sideBarNavigation: "chats",
  setSideBarNavigation: (sideBarNavigation) => set({ sideBarNavigation }),
  myGroups: [],
  setMyGroups: (myGroups) => set({myGroups}),
  groupParticipants: [],
  setGroupParticipants: (groupParticipants) => set({groupParticipants}),
  loggedInUser: null,
  setLoggedInUser: (loggedInUser) => set({loggedInUser}),
  selectedImage: null,
  setSelectedImage: (selectedImage) => set({selectedImage}),
  receiverId : null,
  setReceiverId: (receiverId) => set({receiverId}),  // to fetch the receiver from the clicked by user on the search bar to give params in useCreateChat
  groupFormDivision: false,
  setGroupFormDivision: (groupFormDivision) => set({groupFormDivision}),
  loading: false,
  setLoading: (loading) => set({loading}),
}));
